# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Print versions
        run: |
          node --version
          yarn --version
          npx commitlint --version

      - name: Install dependencies
        run: yarn install

      - name: Check code style
        run: yarn format:check

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Print versions
        run: |
          node --version
          yarn --version
          npx commitlint --version

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
